id: A31973895
title: Lamp Aspiration Prayer (from the Tsok Offering 'A Rain of Blessings')
type: translation
pechas:
- I4565959A
- I3EA4AAA1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:04.616355
  last_modified_at: 2023-01-04 12:46:04.616373
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I4565959A/9358: 04D9
  I3EA4AAA1/59EB: 04D9
